name: Project Review Task Automation

env:
  PROJECT_ID: PVT_kwHOBWzUNM4A9eKK
on:
  push:
  pull_request:
  issues:
  issue_comment:
  pull_request_review:
  pull_request_review_comment:
  release:
  workflow_dispatch:

jobs:
  automate_project_tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Check project status field
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_PROJECT_AUTOMATION }}
        run: |
          echo "automation run"
          curl -X POST \
            -H "Authorization : Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json"\
            -d '{
                "query":"{
                  node(id: \\\"$PROJECT_ID\\\") {
                    ... on ProjectV2 { items(first: 10) {
                      nodes {
                        content {
                          ... on Issue {
                            title number 
                            } 
                          } 
                          fieldValues(first: 10) {
                            nodes {
                              value projectField {
                                name
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }"
              }' \
              https://api.github.com/graphql 
      
