name: Project Review Task Automation

env:
  PROJECT_ID: PVT_kwHOBWzUNM4A9eKK
  GITHUB_TOKEN: ${{ secrets.PAT_PROJECT_AUTOMATION }}
  CLASSIC_GITHUB_TOKEN: ${{ secrets.CLASSIC_GITHUB_TOKEN }}
on:
  push:
  pull_request:
  issues:
  issue_comment:
  pull_request_review:
  pull_request_review_comment:
  release:
  workflow_dispatch:

jobs:
  automate_project_tasks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get previous state
        id: previous
        uses: actions/cache@v4
        with:
          path: prev_review_items.json
          key: project-review-state

      - name: List issues in Review
        id: get_review
        run: |
          curl -s -X POST https://api.github.com/graphql \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d @- <<EOF > current_review_items.json
              {
                "query": "{
                  node(id: \"${PROJECT_ID}\") {
                    ... on ProjectV2 {
                      items(first: 20) {
                        nodes {
                          content {
                            ... on Issue {
                              title
                              number
                            }
                          }
                          fieldValues(first: 20) {
                            nodes {
                              ... on ProjectV2ItemFieldSingleSelectValue {
                                field {
                                  ... on ProjectV2SingleSelectField {
                                    id
                                    name
                                    options {
                                      id
                                      name
                                    }
                                  }
                                }
                                optionId
                              }
                              ... on ProjectV2ItemFieldTextValue {
                                field {
                                  ... on ProjectV2Field {
                                    name
                                  }
                                }
                                text
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }"
              }
          EOF
          echo "review items content"
          cat current_review_items.json

      - name: Create review task
        run: python3 create_review_issues.py
        
